# This workflow will build and deploy the blog to the production folder

name: Deploy Production

on:
  push:
    branches: [ "release" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
    - run: yarn
    - run: yarn build
    - uses: actions/upload-artifact@v4
      with:
        name: build-dir
        path: out
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build-dir
        path: out
      # You may pin to the exact commit or the version.
      # uses: garygrossgarten/github-action-scp@8a27854bb4f124a497a67316e83783efda770119
    - uses: garygrossgarten/github-action-scp@release
      with:
        # Path to the local folder you want to copy.
        local: out
        # Path on the remote server to copy to.
        remote: httpdocs/production
        # Determines if files with  leading dot (.) on folder copy is included
        dotfiles: true
        # If it is a directory, remote files in it will be deleted before the copy is started.
        rmRemote: true
        # Hostname or IP address of the server.
        host: ${{ secrets.HOST }}
        # Username for authentication.
        username: ${{ secrets.SSH_USER }}
        # Port number of the server.
        port: 22
        # Password for password-based user authentication.
        password: ${{ secrets.PASSWORD }}
        # Upload files to temporary file first, then rename once upload completed
        atomicPut: true
              

